# Generated by Django 5.2.5 on 2026-03-24 07:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_ip_address_contact_is_read_contact_subject_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='contacts_co_sent_at_d9e973_idx',
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Marked as read'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
