# Generated by Django 5.2.5 on 2026-03-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('cert', models.CharField(blank=True, max_length=200)),
                ('badge_color', models.CharField(default='secondary', max_length=50)),
                ('provider', models.CharField(blank=True, help_text='e.g., Coursera, Udemy', max_length=100)),
                ('date_earned', models.DateField(blank=True, null=True)),
                ('expires', models.DateField(blank=True, null=True)),
                ('does_not_expire', models.BooleanField(default=False, help_text='Check if this certification never expires')),
                ('credential_id', models.CharField(blank=True, max_length=50, null=True)),
                ('color_rgb', models.CharField(blank=True, default='108,117,125', max_length=20)),
                ('icon_class', models.CharField(blank=True, default='fas fa-certificate', max_length=50)),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('verification_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, upload_to='projects/')),
                ('category', models.CharField(default='Django', max_length=100)),
                ('technologies', models.TextField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon_class', models.CharField(default='fas fa-star', max_length=50)),
                ('proficiency', models.PositiveIntegerField(help_text='0-100')),
                ('color_class', models.CharField(help_text='primary, success, info, warning', max_length=50)),
            ],
            options={
                'ordering': ['-proficiency', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=50)),
                ('color_class', models.CharField(default='primary', max_length=50)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
    ]
