# Generated by Django 5.2.5 on 2026-03-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_project_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skill', models.CharField(help_text="Specific skill e.g., 'Django ORM'", max_length=100)),
                ('issuer', models.CharField(help_text='e.g., Coursera, Credly', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='badges/')),
                ('verification_url', models.URLField(blank=True, null=True)),
                ('date_earned', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
