# Generated by Django 5.2.5 on 2026-03-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_education'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-duration'], 'verbose_name_plural': 'Educations'},
        ),
        migrations.AddField(
            model_name='education',
            name='percentage_or_cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
