# Generated by Django 5.2.5 on 2026-03-07 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_education_options_education_percentage_or_cgpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='value',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
